name: Build and release

on:
  push:
    branches: [ ci ]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - platform: linux/amd64
            arch: x86_64
            base: "ubuntu:jammy"
#          - platform: linux/arm64
#            arch: arm64
#            base: "ubuntu:jammy"
          - platform: linux/arm/v7
            arch: rpi3
            base: "debian:bullseye-slim"
#          - platform: linux/arm/v7
#            arch: rpi3
#          - platform: linux/arm/v7
#            arch: rpi2
#        base:
#          - os: ubuntu
#            codename: jammy

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: rlespinasse/github-slug-action@v4

      - name: Setup qemu for docker
        uses: docker/setup-qemu-action@v3
        if: matrix.target.platform != 'linux/amd64'

      - name: Setup buildx for docker
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.target.platform }}
          outputs: build
          build-args: |
            BASE_IMAGE=${{ matrix.target.base }}
            TARGET_PLATFORM=${{ matrix.target.platform }}
            LR_PLATFORM=${{ matrix.target.arch }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.target.arch }}
          path: |
            build/lr_multi_bomberman_libretro.so
          if-no-files-found: error

  release:
    runs-on: ubuntu-latest

    needs:
      - build

    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v7
        with:
          path: assets
      - name: Create checksum for release assets
        shell: bash
        run: |
          algo="${SHA_ALGORITHM:-256}"
          find assets -type f | while read -r asset; do
            shasum --binary --algorithm "${algo}" "${asset}" >"${asset}.sha${algo}"
          done
      - name: Upload artifacts to GitHub release
        uses: softprops/action-gh-release@v2
        with:
          draft: ${{ !startsWith(github.ref, 'refs/tags/') }}
          files: assets/**
